Chat/Models/JoinViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EC2.Chat.Models
{
    public class JoinViewModel
    {
        [Required]
        public Guid ID { get; set; }
        
        [Required]
        public string PIN { get; set; }
    }
}

Chat/Controllers/ChatroomController.cs
using EC2.Chat.Helpers;
using EC2.Chat.Models;
using EC2.ChatEngine;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace EC2.Chat.Controllers
{
    public class ChatroomController : BaseController<Chatroom>
	{
		private IChatroom room = null;

        [CultureAttribute]
        public ActionResult Create()
		{
			ChatroomViewModel model = new ChatroomViewModel();
			return View(model);
		}

		[HttpPost]
		public ActionResult Create(string Name, string Nick)
		{
			if (string.IsNullOrWhiteSpace(Name)) Name = Resources.LocalizedText.SystemMessages_Anonymous;
            if (string.IsNullOrWhiteSpace(Nick)) Nick = Resources.LocalizedText.SystemMessages_Anonymous;

			ChatResult result = null;
			room = manager.Add(Name, Nick, out result);
			TempData["PIN"] = result.Pin;

			Save();
			return RedirectToAction("Details", new { roomId = room.ChatroomID });
		}

		[HttpPost]
        [CultureAttribute]
		public ActionResult Join(Guid? roomId, string PIN, string Nick)
		{
            if (string.IsNullOrWhiteSpace(Nick)) Nick = Resources.LocalizedText.SystemMessages_Anonymous;

			if (roomId.HasValue)
			{
				var room = manager.Get(roomId.Value);

				if (room != null)
				{
					ChatResult result = room.Join(Nick, PIN);
					if (result.Terminate == true)
					{
                        Error(Resources.LocalizedText.SystemMessages_WrongOrUsedPIN);
						return RedirectToAction("Index", "Home");
					}

					Save();

					TempData["PIN"] = PIN;

					return RedirectToAction("Details", new { roomId = room.ChatroomID });
				}
				else
				{
                    Error(Resources.LocalizedText.SystemMessages_ChatroomNotExist);
					return RedirectToAction("Index", "Home");
				}
			}

            Error(Resources.LocalizedText.SystemMessages_ChatroomNotExist);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public ActionResult Leave(Guid? roomId, string PIN)
		{
			if (roomId.HasValue)
			{
				var room = manager.Get(roomId.Value);
				if (room != null)
				{
					ChatResult result = room.Leave(PIN);

					Save();
				}

                Information(Resources.LocalizedText.SystemMessages_LoggedOffSuccessfully);

				return RedirectToAction("Index", "Home");
			}

            Error(Resources.LocalizedText.SystemMessages_UserPinNotExist);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public ActionResult DeleteRoom(Guid roomId, string PIN)
		{
			ChatResult result = manager.Delete(roomId, PIN);

			Save();

			Error(Resources.LocalizedText.ChatWindow_Messages_OnClose);
			return RedirectToAction("Index", "Home");
		}

        [CultureAttribute]
		public ActionResult Details(Guid? roomId)
		{
			if (roomId.HasValue)
			{
				IChatroom room = manager.Get(roomId.Value);
				ChatroomViewModel model = new ChatroomViewModel();
				if (room != null)
				{
					model.Chatroom = room;
					model.roomId = roomId.Value;

					string PIN = TempData["PIN"] as string;
					TempData.Remove("PIN");
					if (!string.IsNullOrWhiteSpace(PIN))
					{
						model.PIN = PIN;
						model.Users = room.GetUsers(PIN);
						model.IsOwner = room.IsOwner(PIN);
						var mFile = ((Chatroom)room).Messages.FirstOrDefault(it => it.MessageStatus == Message.Status.File);
						model.isFile = mFile != null;
						model.File = model.isFile ? mFile.File.Name : null;
					}

					if (room != null)
						return View(model);
				}
			}

            Error(Resources.LocalizedText.SystemMessages_ChatroomNotExist);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
        [CultureAttribute]
		public ActionResult Details(Guid? roomId, string PIN)
		{
			ChatroomViewModel model = new ChatroomViewModel();
			room = null;
			if (roomId.HasValue)
			{
				room = manager.Get(roomId.Value);

				if (room != null)
				{
					model.Chatroom = room;
					model.PIN = PIN;
					model.roomId = roomId.Value;
					model.IsOwner = room.IsOwner(PIN);
				}

				model.Users = room.GetUsers(model.PIN);

				Save();

				return View(model);
			}

            Error(Resources.LocalizedText.SystemMessages_ChatroomNotExist);
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public ActionResult ResetIncidents(Guid roomId, string PIN)
		{
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
				room.ClearIncidents(PIN);

				return Json(null, JsonRequestBehavior.DenyGet);
			}
			else
			{
                return Json(Resources.LocalizedText.SystemMessages_ChatroomNotExist, JsonRequestBehavior.DenyGet);
			}
		}

		[HttpPost]
		public JsonResult Kick(Guid roomId, string PIN, Guid UserId)
		{
			var room = manager.Get(roomId);

			if (room != null)
			{
				var chat = room.Kick(PIN, UserId);
				Save();
				return generateJsonChat(chat, null, null);
			}
            return Json(Resources.LocalizedText.SystemMessages_ChatroomNotExist, JsonRequestBehavior.DenyGet);
		}

		[HttpPost]
		[ValidateInput(false)]
		public JsonResult Push(Guid roomId, string PIN, string Message)
		{
			Message = Regex.Replace(Message, "<", "&lt;");
			Message = Regex.Replace(Message, ">", "&gt;");
			Message = Regex.Replace(Message, "\"", "&quot;");
			Message = Regex.Replace(Message, "'", "&#39;");
			string accessMessage = string.Empty;

			ChatResult result = null;
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
                result = room.Push(PIN, Message);

				Save();
			}

            if (result == null && !string.IsNullOrEmpty(PIN)) accessMessage = Resources.LocalizedText.SystemMessages_YoursSlotClosed;
            if (room == null) accessMessage = Resources.LocalizedText.SystemMessages_ChatClosed;

			return generateJsonChat(result, accessMessage, PIN);
		}

		[HttpPost]
		public JsonResult Pull(Guid roomId, string PIN)
		{
			string accessMessage = string.Empty;

			ChatResult result = null;
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
				result = room.Pull(PIN);
			}

            if (result == null && !string.IsNullOrEmpty(PIN)) accessMessage = Resources.LocalizedText.SystemMessages_YoursSlotClosed;
            if (room == null) accessMessage = Resources.LocalizedText.SystemMessages_ChatClosed;
            
			return generateJsonChat(result, accessMessage, PIN);
		}

		[HttpPost]
		public JsonResult AddSlot(Guid roomId, string PIN)
		{
			var chatroom = manager.Get(roomId);
            if (chatroom == null) return Json(Resources.LocalizedText.SystemMessages_ChatroomNotExist, JsonRequestBehavior.DenyGet);
			var result = chatroom.AddSlot(PIN);
			return generateJsonChat(result, null, null); //Json(null, JsonRequestBehavior.DenyGet);
		}

		[HttpPost]
		public JsonResult ExtendTime(Guid roomId, string PIN)
		{
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
				ChatResult result = room.ExtendTime(PIN);

				return Json(null, JsonRequestBehavior.DenyGet);
			}
			else
			{
                return Json(Resources.LocalizedText.SystemMessages_ChatroomNotExist, JsonRequestBehavior.DenyGet);
			}
		}

		/// <summary>
		/// Akcja odpowiadająca za upload pliku na serwer
		/// </summary>
		/// <param name="roomId">ID chatu</param>
		/// <param name="PIN">PIN osoby wywołującej akcje</param>
		/// <param name="FileStream">Plik do uploadu</param>
		/// <returns>Zwraca informacje o stanie akcji</returns>
		[HttpPost]
		public JsonResult UploadFile(Guid roomId, string PIN, HttpPostedFileBase FileStream)
		{
			if (FileStream != null && FileStream.ContentLength > 0 && FileStream.FileName != null)
			{
				string accessMessage = string.Empty;

				ChatResult result = null;
				IChatroom room = manager.Get(roomId);
				if (room != null && FileStream.ContentLength > 0 && FileStream.ContentLength < 8192 * 1024)
				{
					using (var mem = new System.IO.MemoryStream())
					{
						var serial = new System.Web.Script.Serialization.JavaScriptSerializer {MaxJsonLength = 8192*1024};
						FileStream.InputStream.CopyTo(mem);
						var contents = mem.ToArray();
						var a = serial.Serialize(contents);
						var name = FileStream.FileName.Contains("\\") ? 
							FileStream.FileName.Split('\\').Last() : 
							FileStream.FileName;
						result = room.Push(PIN, a, FileStream.ContentType, name);
					}
					Save();
				}
				else
                    accessMessage = Resources.LocalizedText.SystemMessages_FileToBig;
                if (room == null) accessMessage = Resources.LocalizedText.SystemMessages_ChatClosed;

				return generateJsonChat(result, accessMessage, PIN);
			}
			return null;
		}

		/// <summary>
		/// Usunięcie pliku z serwera
		/// </summary>
		/// <param name="roomId">ID chatu</param>
		/// <param name="PIN">PIN osoby wywołującej akcje</param>
		/// <returns>Zwraca informacje o stanie akcji</returns>
		[HttpPost]
		public JsonResult DeleteFile(Guid roomId, string PIN, int ID)
		{
			string accessMessage = string.Empty;

			ChatResult result = null;
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
				result = room.DelFile(PIN, ID);

				Save();
			}

            if (result == null && !string.IsNullOrEmpty(PIN)) accessMessage = Resources.LocalizedText.SystemMessages_YoursSlotClosed;
            if (room == null) accessMessage = Resources.LocalizedText.SystemMessages_ChatClosed;

			return generateJsonChat(result, accessMessage, PIN);
		}

		/// <summary>
		/// Pobieranie pliku z serwera
		/// </summary>
		/// <param name="roomId">ID chatu</param>
		/// <param name="PIN">PIN osoby wywołującej akcje</param>
		/// <returns>Zwraca informacje o stanie akcji</returns>
		public FileResult DownFile(Guid roomId, string PIN, int ID)
		{
			IChatroom room = manager.Get(roomId);
			if (room != null)
			{
				var file = room.GetFile(PIN, ID);

				var serial = new System.Web.Script.Serialization.JavaScriptSerializer();
				serial.MaxJsonLength = 8192 * 1024;
				try
				{
					var baContent = serial.Deserialize(file.Content, typeof(byte[]));

Chat/Controllers/HomeController.cs
using EC2.Chat.Helpers;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace EC2.Chat.Controllers
{
    
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        [CultureAttribute]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Language(string culture_)
        {
            CultureAttribute.SavePreferredCulture(Response, culture_, 1);

            System.Globalization.CultureInfo cultureInfo = GetCulture(culture_);

            Thread.CurrentThread.CurrentCulture = cultureInfo;
            Thread.CurrentThread.CurrentUICulture = cultureInfo;
            
            return RedirectToAction("Index");
        }

        [CultureAttribute]
        public JsonResult LocalizeJSON()
        {
            CultureInfo culture_ = GetCulture(Request);
            Dictionary<object, object> dict = ReadResources("LocalizedText", culture_);
            
            return Json(dict, JsonRequestBehavior.AllowGet);
        }

        private static Dictionary<object, object> ReadResources(string classKey,
                                                           CultureInfo requestedCulture)
        {
            var resourceManager = new ResourceManager("Resources." + classKey,
                                                Assembly.Load("App_GlobalResources"));
            using (var resourceSet =
                resourceManager.GetResourceSet(CultureInfo.InvariantCulture, true, true))
            {

                return resourceSet
                    .Cast<DictionaryEntry>()
                    .ToDictionary(x => x.Key,
                         x => resourceManager.GetObject((string)x.Key, requestedCulture));
            }

        }

        private CultureInfo GetCulture(HttpRequestBase request)
        {
            var culture = "";
            var cookie = request.Cookies["_Culture"];
            if (cookie != null)
                culture = cookie.Values["language"];
            else
            {
                var lang = request.UserLanguages.FirstOrDefault();
                culture = lang;
            }
            
            CultureInfo cultureInfo;
            try
            {
                cultureInfo = CultureInfo.CreateSpecificCulture(culture);
            }
            catch (Exception e)
            {
                cultureInfo = CultureInfo.CreateSpecificCulture("en-US");
            }
            return cultureInfo;
        }

        private CultureInfo GetCulture(string culture_)
        {
            CultureInfo cultureInfo;
            try
            {
                cultureInfo = CultureInfo.CreateSpecificCulture(culture_);
            }
            catch (Exception e)
            {
                cultureInfo = CultureInfo.CreateSpecificCulture("en-US");
            }
            return cultureInfo;
        }

        public HomeController()
        {
            //var cultureString = GetCultureToApply();
            //var cultureInfo = CultureInfo.CreateSpecificCulture(cultureString);
            //Thread.CurrentThread.CurrentCulture = cultureInfo;
            //Thread.CurrentThread.CurrentUICulture = cultureInfo;
        }

    }
}

Chat/Views/Home/Create.cshtml
@model EC2.Chat.Models.ChatroomViewModel


@using (Html.BeginForm("Create", "Chatroom"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.Hidden("NewRoom", true)
    <div class="editor-label">
            @Resources.LocalizedText.InitiationWindow_Name
        </div>
        <div class="editor-field">
          @Html.TextBox("Name")
        </div>
        <div class="editor-label">
            @Resources.LocalizedText.InitiationWindow_Nick
        </div>
        <div class="editor-field">
            @Html.TextBox("Nick")
        </div>
        
        <p>
            <input type="submit" value="@Resources.LocalizedText.InitiationWindow_CreateButton" />
        </p>
}

Chat/Views/Home/CreateLight.cshtml
@model EC2.Chat.Models.ChatroomViewModel


@using (Html.BeginForm("Create", "ChatroomLite"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.Hidden("NewRoom", true)
    <div class="editor-label">
            Nazwa
        </div>
        <div class="editor-field">
          @Html.TextBox("Name")
        </div>
        <div class="editor-label">
            Nick
        </div>
        <div class="editor-field">
            @Html.TextBox("Nick")
        </div>
        
        <p>
            <input type="submit" value="Utwórz" />
        </p>
}

Chat/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Main Page";
}


<div id="dialogJoin" style="display: none;" title="@Resources.LocalizedText.InitiationWindow_TitleJoin">
    @{
        Html.RenderPartial("Join");
    }
</div>


<div id="dialogCreate" style="display: none;" title="@Resources.LocalizedText.InitiationWindow_TitleNew">
    @{
        Html.RenderPartial("Create");
    }
</div>

<div id="dialogLightJoin" style="display: none;" title="@Resources.LocalizedText.InitiationWindow_TitleJoin">
    @{
        Html.RenderPartial("JoinLight");
    }
</div>


<div id="dialogLightCreate" style="display: none;" title="@Resources.LocalizedText.InitiationWindow_TitleNew">
    @{
        Html.RenderPartial("CreateLight");
    }
</div>


@{
	Html.RenderPartial("maincontent");
}

<div class="commercial">
    <hr class="white" />
    <center>
        <a href="http://demo.ec2.pl/AdServerService/AD/URL?id=12" target="_blank">
            <img id="imgPreview" width="970" height="250" src="http://demo.ec2.pl/AdServerService/AD?&Id=12" alt="Ad">
        </a>
    </center>
</div>

@section Scripts
    {

	

	<script>

		$(function () {

			$("#openerJoin").click(function () {
				$("#dialogJoin").dialog("open");
			});

			$("#openerLightJoin").click(function () {
				$("#dialogLightJoin").dialog("open");
			});

			$("#openerCreate").click(function () {
				$("#dialogCreate").dialog("open");
			});

			$("#openerLightCreate").click(function () {
				$("#dialogLightCreate").dialog("open");
			});

			$("#dialogCreate").dialog({
				autoOpen: false,
				modal: true,
				resizable: false,
				show: {
					effect: "blind",
					duration: "fast"
				},
				hide: {
					effect: "blind",
					duration: "fast"
				}
			});

			$("#dialogLightCreate").dialog({
				autoOpen: false,
				modal: true,
				resizable: false,
				show: {
					effect: "blind",
					duration: "fast"
				},
				hide: {
					effect: "blind",
					duration: "fast"
				}
			});
			$("#dialogJoin").dialog({
				autoOpen: false,
				modal: true,
				resizable: false,
				minWidth: 380,
				show: {
					effect: "blind",
					duration: "fast"
				},
				hide: {
					effect: "blind",
					duration: "fast"
				}
			});

			$("#dialogLightJoin").dialog({
				autoOpen: false,
				modal: true,
				minWidth: 380,
				resizable: false,
				show: {
					effect: "blind",
					duration: "fast"
				},
				hide: {
					effect: "blind",
					duration: "fast"
				}
			});
		});
	</script>
}

Chat/Views/Home/Join.cshtml
@model EC2.Chat.Models.ChatroomViewModel


@using (Html.BeginForm("Join", "Chatroom"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



    <div class="editor-label">
        @Resources.LocalizedText.InitiationWindow_PIN
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.PIN)
        @Html.ValidationMessageFor(model => model.PIN)
    </div>

    <div class="editor-label">
        @Resources.LocalizedText.InitiationWindow_RoomId
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.roomId,
            new Dictionary<string, object>(){ 
            {"style", "min-width: 300px;"}, 
            {"data-val", "true"}, 
            {"data-val-required","The Id pokoju field is required."  },
            {"class","text-box"  }
            })

        <span class="field-validation-valid" data-valmsg-for="roomId" data-valmsg-replace="true"></span>
    </div>

    <div class="editor-label">
        Nick
    </div>
    <div class="editor-field">
        @Html.TextBox("Nick")
    </div>

       

    <p>
        <input type="submit" value="@Resources.LocalizedText.InitiationWindow_JoinButton" />
    </p>
}

Chat/Views/Home/JoinLight.cshtml
@model EC2.Chat.Models.ChatroomViewModel


@using (Html.BeginForm("Join", "ChatroomLite"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



    <div class="editor-label">
        Id pokoju
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.roomId,
            new Dictionary<string, object>(){ 
            {"style", "min-width: 300px;"}, 
            {"data-val", "true"}, 
            {"data-val-required","The Id pokoju field is required."  },
            {"class","text-box"  }
            })

        <span class="field-validation-valid" data-valmsg-for="roomId" data-valmsg-replace="true"></span>
    </div>

    <div class="editor-label">
        Nick
    </div>
    <div class="editor-field">
        @Html.TextBox("Nick")
    </div>

       

    <p>
        <input type="submit" value="Dołącz" />
    </p>
}